version: "3"
services:
  # mysql
  mysql:
    image: mysql:5.7.17
    restart: always
    container_name: product_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    network_mode: bridge
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # redis
  redis:
    network_mode: bridge
    container_name: product_redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"